server:
#  ssl:
#    key-store: classpath:keystore/baeldung.p12
#    key-store-password: guilherme
#    key-store-type: PKCS12
#    key-alias: baeldung
#    key-password: guilherme
  port: 8080
  servlet:
    context-path: /v1
#
## The format used for the keystore. It could be set to JKS in case it is a JKS file
#  server.ssl.key-store-type=PKCS12
#  # The path to the keystore containing the certificate
#  server.ssl.key-store=classpath:keystore/baeldung.p12
#  # The password used to generate the certificate
#  server.ssl.key-store-password=password
#  # The alias mapped to the certificate
#  server.ssl.key-alias=baeldung
elastic:
  password: PGzvl6tSI180uxQLHSk3KXrC
  username: elastic
  host: "docfynd.es.us-central1.gcp.cloud.es.io"

openai:
  service-url: "https://api.us-south.natural-language-understanding.watson.cloud.ibm.com/instances/9b895e6e-b3fb-4e8c-8871-faf09b502ff2"
  api-key: "1hIEMLga1OvjEUX8dNjEWYfjKWHbevV3s7vDQsXoFQbP"

